spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ajs?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1111
  jpa:
    generate-ddl: true
grokonez:
  app:
    jwtSecret: jwtGrokonezSecretKey
    jwtExpiration: 86400